[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
runner = "qemu-system-aarch64 -machine virt -cpu cortex-a72 -smp 2 -m 1G -nographic -kernel"
rustflags = [
    "-C", "link-arg=-T./kernel/linker.ld",
    "-C", "link-arg=--nmagic"
]

[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]